.PHONY: clean All

All:
	@echo "----------Building project:[ generic_function03 - Debug ]----------"
	@cd "generic_function03" && "$(MAKE)" -f  "generic_function03.mk"
clean:
	@echo "----------Cleaning project:[ generic_function03 - Debug ]----------"
	@cd "generic_function03" && "$(MAKE)" -f  "generic_function03.mk" clean
